### ISSUE TITLE
Support for 16KB page size

### ISSUE THREAD

**Issue by HerrHofrat** [crow-misia/libyuv-android#123]
Hello,
with Android 15 devices can support 16kb page size, however all native libraries need to be adapted - see https://developer.android.com/guide/practices/page-sizes. Can you please add support for it in your library? As you are already on AGP 8.7.0 and NDK 27 I think you only need to add the following line in your Application.mk
```
APP_SUPPORT_FLEXIBLE_PAGE_SIZES := true
```

Thanks&Regards

**Comment by crow-misia** [comment]
It will take some time, it will deal with it.

**Comment by crow-misia** [comment]
Released a fix in https://github.com/crow-misia/libyuv-android/releases/tag/v0.36.0
