### ISSUE TITLE
For some reaosn I cannot install the library neither form mavenCentral nor from jitpack

### ISSUE THREAD

**Issue by MrCsabaToth** [crow-misia/libyuv-android#16]
First I tried `implementation 'io.github.crow-misia.libyuv:libyuv-android:v0.25.0'`

> Unresolved dependencies
> Could not resolve io.github.crow-misia.libyuv:libyuv-android:v0.25.0.

Then I thought `sudo make me a sandwich` and tried jitpack

`implementation 'com.github.crow-misia:libyuv-android:v0.25.0'` but the Gradle Sync fails with that too. I don't understand why.

**Comment by crow-misia** [comment]
Cannot be installed via jitpack because the artifact cannot be signed.

**Comment by MrCsabaToth** [comment]
I see it in the Maven repo: https://search.maven.org/search?q=g:io.github.crow-misia.libyuv
Maybe one of the transitive dependencies?

**Comment by crow-misia** [comment]
Inclusion of the v, in a badge, is dependent on the Shields service and cannot be removed. Please recognize it as such.

https://github.com/badges/shields/issues/3200
