### ISSUE TITLE
can you create nativeI420ToJpeg and other method

### ISSUE THREAD

**Issue by heaveninfosoft** [crow-misia/libyuv-android#2]
public static final native void nativeStereoI420Frame(byte[] bArr, byte[] bArr2, byte[] bArr3, int i, int i2);

	public static final native void nativeStereoI420FrameBuffer(byte[] bArr, ByteBuffer byteBuffer, byte[] bArr2, int i, int i2);

	public static final native int nativeI420ToJpeg(byte[] bArr, byte[] bArr2, int i, int i2, int i3);

**Comment by crow-misia** [comment]
These two method not exists in libyuv, what are they?


`
public static final native void nativeStereoI420Frame(byte[] bArr, byte[] bArr2, byte[] bArr3, int i, int i2);
public static final native void nativeStereoI420FrameBuffer(byte[] bArr, ByteBuffer byteBuffer, byte[] bArr2, int i, int i2);
`

Also, if you want to convert I420 image to JPEG image, you should use android.graphics.YuvImage#compressToJpeg.
