### ISSUE TITLE
Android 12 / Android 13 Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR)

### ISSUE THREAD

**Issue by goncalocg** [crow-misia/libyuv-android#21]
Hello!

I'm having this ...
`Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x6ef3bfb000 in tid 5692 (GLThread 81), pid 5602`

... when converting from a AbgrBuffer to a i420Buffer only on Android 12 and/or Android 13.

The code is running here:

`val i420Buffer = I420Buffer.allocate(width, height)
buffer.convertTo(i420Buffer)
handleI420Buffer(i420Buffer, width, height)`

And the crash is on
`buffer.convertTo(i420Buffer)`

Do you have any ideas about what can I do?
Thank you

**Comment by crow-misia** [comment]
I don't know how the ABGRBuffer of `buffer` variable was generated.
If it was generated by a method other than `allocate` method, `width`, `height`, and `rowStride` may differ from the actual data.

**Comment by goncalocg** [comment]
it was created with
`val buffer = AbgrBuffer.allocate(width, height)`
`buffer.asBuffer().put(data)`

where data is a ByteBuffer.
Do you think I need the rowString to prevent this?
