### ISSUE TITLE
0.29.0 seems incompatible with CameraX/Camera2 1.3.0

### ISSUE THREAD

**Issue by lorenz-jumio** [crow-misia/libyuv-android#34]
We are using CameraX/Camera2 apis in one of our projects, version `1.3.0` and are exploring libyuv-android atm. While everything works well with version `0.28.0`, we are observing FATAL EXCEPTIONS when upgrading to `0.29.0`. Any advice?

**Comment by crow-misia** [comment]
0.29.0 fixes a buffer size calculation bug, though. It may have been degrade.
Please let me know which class and method you used.

In addition, if you could provide a stack trace, that would be even better.

**Comment by lorenz-jumio** [comment]
Stack trace is quite minimal:
```text
FATAL EXCEPTION: CameraX-core_camera_0
java.lang.AbstractMethodError: abstract method "androidx.camera.core.impl.CameraFactory androidx.camera.core.impl.CameraFactory$Provider.newInstance(android.content.Context, androidx.camera.core.impl.CameraThreadConfig, androidx.camera.core.CameraSelector, long)"
at androidx.camera.core.CameraX.lambda$initAndRetryRecursively$2$androidx-camera-core-CameraX(CameraX.java:306)
at androidx.camera.core.CameraX$$ExternalSyntheticLambda3.run(Unknown Source:10)
```

We are using `ProcessCameraProvider.getInstance(context)` and adding the listener on the returned future with the main executor.

By applying 

```groovy
exclude group: 'androidx.camera', module: 'camera-core'
```

to libyuv-android dependency, everything seems to work fine though with camerax `1.3.0`

**Comment by crow-misia** [comment]
Since this library depends only on the camerax-core library, perhaps the camerax version is different between core and others.

Version 0.30.0 is released to remove the dependency on camerax.
It resolves version mismatch.

**Comment by lorenz-jumio** [comment]
Thanks, I tried with `0.30.0` and everything works well with camerax 1.3.0 (without the exclude) 👍
