### ISSUE TITLE
Add YUY2 packed format conversion

### ISSUE THREAD

**Issue by dp-singh** [crow-misia/libyuv-android#4]
Can you also add the support to convert YUY2 (Known as YUY2, YUYV, V422, or YUNV) to other YUV formats?

**Comment by crow-misia** [comment]
Sorry,I don't have enough resource to do.
PR are welcome.

**Comment by crow-misia** [comment]
@dp-singh 
Added support for YUY2(YUY2 -> I420,I422,ARGB,NV12) with v0.18.0

**Comment by dp-singh** [comment]
Thanks, @crow-misia for the update.

Is there any reason behind skipping  `YUY2 -> NV21` conversion?

**Comment by crow-misia** [comment]
This is because libyuv itself does not support it.
