### ISSUE TITLE
lib name conflict

### ISSUE THREAD

**Issue by garbe-github-support** [crow-misia/libyuv-android#54]
Your project's so library is named libyuv, but the libyuv library itself is also called libyuv because we also use libyuv in our project. If we rely on your project now, there will be conflicts. Only the original libyuv has been packaged in apk. If we want to call the method you added to the so library, an error will be reported。 How can I solve this problem?

**Comment by Tobi1025** [comment]
("/system/lib64/libyuv.so") needed or dlopened by "/apex/com.android.art/lib64/libnativeloader.so" is not accessible for the namespace: [name="clns-5"xxxx

**Comment by Tobi1025** [comment]
I have the same issue , it seems that your so library is in conflict with the system's

**Comment by crow-misia** [comment]
Renamed so library from libyuv.so to libyuv_android.so.

Released as v0.33.0

**Comment by crow-misia** [comment]
Closed the issue. If anything happens, please make a new issue.
