### ISSUE TITLE
[Feature request] Extend android.media.Image extensions to fill YUV_420 buffers out of Bitmap

### ISSUE THREAD

**Issue by adjorno** [crow-misia/libyuv-android#6]
Hi,

I am trying to mock Camera API in order to run my tests in CI. The idea is to create an alternative producer of YUV frames instead of Camera hardware.
I would like to have this alternative based on android.media.ImageWriter so it could produce YUV frames converted from predefined jpeg/png/bitmap etc. Something like:

```kotlin
suspend fun startFrameProducer(target: Surface) {
   val testImageBitmap = BitmapFactory.decodeBitmap(testFile)
   val imageWriter = ImageWriter.newInstance(target, 1)
   val imageFrame = imageWriter.dequeueInputImage()
   imageFrame.fillYUVBuffers(testImageBitmap) // TODO: This is something I am missing
   imageWriter.queueInputImage(imageFrame)
}
```

Can you help how to use existing API of this library in order to fill buffers correctly with YUV420 pixel format?

**Comment by crow-misia** [comment]
I think it can be done as follows.

1. Create a Buffer using Bitmap#copyPixelsToBuffer or Bitmap#getPixels
2. Implement android.media.Image.Plane.
3. Implement android.media.Image.

I don't think this is within the scope of this library.

**Comment by adjorno** [comment]
Thank you for such a quick response.

This is exactly the domain (constructing planes: y,u,v values) I have limited knowledge and I would love to have some reliable third-party solution which could help me with this.

For some reason most of the samples show how to convert YUV Image into RGBA Bitmap, but there is none for the other way around.

I would appreciate it if you could guide me how the RGBA buffer from Bitmap could be split into planes with correct values.

**Comment by crow-misia** [comment]
If you want to get Y/U/V buffers from a Bitmap, you can use the following code (1920=width, 1080=height)
```kotlin
  val bitmap = Bitmap.createBitmap(1920, 1080, Bitmap.Config.ARGB_8888)

  val argbBuffer = AbgrBuffer.allocate(1920, 1080)
  bitmap.copyPixelsToBuffer(argbBuffer.asBuffer())
  val yuvBuffer = I420Buffer.allocate(1920, 1080)
  argbBuffer.convertTo(yuvBuffer)

  // Y/U/V ByteBuffers.
  // yuvBuffer.planeY.buffer
  // yuvBuffer.planeU.buffer
  // yuvBuffer.planeV.buffer
```

**Comment by adjorno** [comment]
Just found some time to come up with the sample app based on your recommendation. It works on emulator (both archs M1 arm64 and Intel Macbook x86) but unfortunately the result on physical devices is inconsistent:

Source image (taken from https://en.wikipedia.org/wiki/File:Andrew_Hink_selfie.jpeg)

| Original          | Emulator           | Pixel 5 (Android 12)  |
| ------------- |:---------------:| --------------------:|
| ![selfie](https://user-images.githubusercontent.com/22169804/173230357-f1026f7f-5460-4f3a-b8e6-62da468d7ed2.jpeg)    | ![Screenshot_1655031178](https://user-images.githubusercontent.com/22169804/173230385-70a352e2-5418-4b6c-8717-83d716a113b0.png) | ![photo1655032262](https://user-images.githubusercontent.com/22169804/173230498-0bf69865-ec56-4228-8835-34cff2314323.jpeg) |

The sample app project can be found here: https://github.com/adjorno/Bitmap2YUV

Can it be some inconsistency in the native library?

**Comment by crow-misia** [comment]
Since Android 420 is NV21, it is possible to convert from a Bitmap image by converting Image to NV21Buffer.

Image rowStribe and width are not equal, so size of data per row is different between Image and I420Buffer, resulting in image misalignment.

If Buffer is created from Image, rowStribe of Image is used.
```kotlin
    private fun prepareImage(width: Int, height: Int): ArgbBuffer {
        return argbBuffer ?: run {
//                bitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888).apply {
//                    eraseColor(Color.BLUE)
//                }
            bitmap = BitmapFactory.decodeStream(assets.open("selfie.jpeg")).scale(width, height)
            ArgbBuffer.allocate(width, height).also {
                bitmap?.copyPixelsToBuffer(it.asBuffer())
                argbBuffer = it
            }
        }
    }

    private fun startRendering() {
        imageWriter?.let { imageWriter ->
            running = true
            lifecycleScope.launch(Dispatchers.IO) {
                while (running) {
                    delay(1000)
                    val image = imageWriter.dequeueInputImage()
                    val buffer = prepareImage(image.width, image.height)
                    buffer.convertTo(image.toNv21Buffer())
                    imageWriter.queueInputImage(image)
                }
            }
        }
    }
```

Width of TextureView needs to be adjusted to be a multiple of 16.
```
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        textureView = TextureView(this)
        textureView.layoutParams = FrameLayout.LayoutParams(1088, 1900, Gravity.CENTER)
        textureView.surfaceTextureListener = this
        setContentView(textureView)
    }

    private fun prepareImage(width: Int, height: Int): Nv21Buffer {
        return yuvBuffer ?: run {
            Nv21Buffer.allocate(width, height).also {
                yuvBuffer = it
//                bitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888).apply {
//                    eraseColor(Color.BLUE)
//                }
                bitmap = BitmapFactory.decodeStream(assets.open("selfie.jpeg")).scale(width, height)
                val argbBuffer = ArgbBuffer.allocate(width, height)
                bitmap?.copyPixelsToBuffer(argbBuffer.asBuffer())
                argbBuffer.convertTo(it)
            }
        }
    }

    private fun startRendering() {
        imageWriter?.let { imageWriter ->
            running = true
            lifecycleScope.launch(Dispatchers.IO) {
                while (running) {
                    delay(1000)
                    val image = imageWriter.dequeueInputImage()
                    val yuvBuffer = prepareImage(image.width, image.height)
                    val bufferVU = yuvBuffer.planeVU.buffer
                    val capacityVU = bufferVU.limit()
                    val bufferV = bufferVU.let {
                        it.position(0)
                        it.limit(capacityVU - 1)
                        it.slice()
                    }
                    val bufferU = bufferVU.let {
                        it.position(1)
                        it.limit(capacityVU)
                        it.slice()
                    }

                    yuvBuffer.planeY.buffer.position(0)
                    image.planes[0].buffer.put(yuvBuffer.planeY.buffer)
                    image.planes[1].buffer.put(bufferU)
                    image.planes[2].buffer.put(bufferV)
                    imageWriter.queueInputImage(image)
                }
            }
        }
    }
```

**Comment by adjorno** [comment]
>> If Buffer is created from Image, rowStribe of Image is used.

This idea indeed improved the situation dramatically. But still not ideal result on a physical device:
| Emulator        | Pixel 5           | 
| ------------- |:-------------:|
| ![emulator](https://user-images.githubusercontent.com/22169804/173431941-bfe63bb4-8c96-44c0-b62e-1b3303b6bb43.png)     | ![pixel5](https://user-images.githubusercontent.com/22169804/173432051-b7245d57-77a8-4e18-a04f-ee58a94e9889.png) |

```kotlin
    private fun createImageWriter(surface: Surface, width: Int, height: Int) {
        yuvBuffer = I420Buffer.allocate(width, height).apply {
            val abgrBuffer = AbgrBuffer.allocate(width, height).apply {
                BitmapFactory.decodeStream(assets.open("selfie.jpeg")).scale(width, height).copyPixelsToBuffer(asBuffer())
            }
            abgrBuffer.convertTo(this)
        }
        imageWriter = ImageWriter.newInstance(surface, 1, ImageFormat.YUV_420_888)
        startRendering()
    }

    private fun startRendering() {
        imageWriter?.let { imageWriter ->
            yuvBuffer?.let { yuvBuffer ->
                running = true
                lifecycleScope.launch(Dispatchers.IO) {
                    while (running) {
                        delay(1000)
                        val image = imageWriter.dequeueInputImage()
                        yuvBuffer.convertTo(image.toI420Buffer())
                        imageWriter.queueInputImage(image)
                    }
                }
            }
        }
    }
```

Thank you for support! Your library indeed does the job. There is just something more that I can't get.

**Comment by crow-misia** [comment]
````
           yuvBuffer.convertTo(image.toNv12Buffer())
```
Please try to do this.
