### ISSUE TITLE
java.lang.IllegalStateException: RGBAToI420 failed

### ISSUE THREAD

**Issue by dzq0906** [crow-misia/libyuv-android#63]
┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    │ DefaultDispatcher-worker-8, com.cloud.rtcgesture.CloudRtcGestureApplication$ExceptionHandler.uncaughtException(CloudRtcGestureApplication.kt:157)
                                                                                                    ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
                                                                                                    │ args[0] = ExceptionHandler
                                                                                                    │ args[1] = Uncaught Exception occurred!
                                                                                                    │ args[2] = java.lang.IllegalStateException: RGBAToI420 failed
                                                                                                    │ 	at io.github.crow_misia.libyuv.Yuv.convertRGBAToI420(Native Method)
                                                                                                    │ 	at io.github.crow_misia.libyuv.RgbaBuffer.convertTo(RgbaBuffer.kt:23)
                                                                                                    │ 	at com.cloud.rtcgesture.server.RtcServer$createRGBAFrame$1.invokeSuspend(RtcServer.kt:468)
                                                                                                    │ 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    │ 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    │ 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
                                                                                                    │ 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
                                                                                                    │ 	at kotlinx.coroutines.scheduling.CoroutineSch
                                                                                                    └────────────────────────────────────────────────────────────────────────────────────────────────────────────────

**Comment by dzq0906** [comment]
val directBuffer = ByteBuffer.allocateDirect(RGBABuffer.size)
            directBuffer.put(RGBABuffer)
            directBuffer.rewind()

            var stride = RowStride(stride)
            var plane = PlanePrimitive(stride, directBuffer)
            var rgba = RgbaBuffer.wrap(plane, width, height, Rect())

            var i420 = I420Buffer.allocate(width, height, Rect())
            var nv21 = Nv21Buffer.allocate(width, height)

            rgba.convertTo(i420)

**Comment by crow-misia** [comment]
Caused by empty area that is cropped.
Do not use Rect() without parameters or use a sized Rect.

```
var rgba = RgbaBuffer.wrap(plane, width, height, Rect(0, 0, width, height))
var i420 = I420Buffer.allocate(width, height, Rect(0, 0, width, height))
```
or
```
var rgba = RgbaBuffer.wrap(plane, width, height)
var i420 = I420Buffer.allocate(width, height)
```

**Comment by dzq0906** [comment]
thank you

**Comment by dzq0906** [comment]
var rgba = RgbaBuffer.wrap(plane, width, height)      There is no such API

**Comment by crow-misia** [comment]
Oh, implementation was omitted.

**Comment by crow-misia** [comment]
release 0.34.0 to add wrap method without cropRect parameter.

**Comment by dzq0906** [comment]
![image](https://github.com/crow-misia/libyuv-android/assets/67351747/987d699b-c284-4fe6-a20e-d3472243b8b1)
There is an issue with the converted image , Is it the latest version of libyuv

**Comment by dzq0906** [comment]
![image](https://github.com/crow-misia/libyuv-android/assets/67351747/38c54d36-aea2-4ea6-aa55-ffd6ab355b75)

**Comment by dzq0906** [comment]
![image](https://github.com/crow-misia/libyuv-android/assets/67351747/1ca854ef-4988-4c6a-9445-c27ef221fb25)
i420.planeY.buffer + i420.planeU.buffer

**Comment by dzq0906** [comment]
![image](https://github.com/crow-misia/libyuv-android/assets/67351747/ddcb815e-0cdf-442b-b359-ca840bc5aced)

**Comment by dzq0906** [comment]
The problem has been resolved , API ConvertToI420 used by Rgba, There will be color difference, There is no problem using ABGRToI420

**Comment by crow-misia** [comment]
please can you write about what happened and how it was resolved, for others?

**Comment by dzq0906** [comment]
![image](https://github.com/crow-misia/libyuv-android/assets/67351747/d7b5edb1-1e8f-4009-ab35-5b105f0f2a06)
By using AbgrBuffer, there will be no color difference issue

**Comment by crow-misia** [comment]
Thanks.
