### ISSUE TITLE
libyuv version 1892  build erro

### ISSUE THREAD

**Issue by Roc-egg** [crow-misia/libyuv-android#95]
compilation error using the latest version, please help me.

![image](https://github.com/user-attachments/assets/817b7ef9-4f89-4e7d-aaa0-01b5d41ef9e5)

**Comment by crow-misia** [comment]
This is occurring because Android NDK is not supporting ARM64's dot product instruction.

Remove all code that uses dot product instruction, or add ifdef to disable it at compile time.

I have not started to fix this issue because there are too many changes to be made.

**Comment by crow-misia** [comment]
Resolved in v0.35.0.
